!USE_BELOW_LANDING_SITE = 0
!USE_HITBOX_VIEWER = 0

!hard_mode_flag = $09EC

lorom

incsrc freespace.asm
incsrc assertpc.asm
incsrc enemies.asm
incsrc physics_constants.asm
incsrc patches/easy_blue_suit.asm
incsrc patches/easy_grapple.asm
incsrc patches/easy_xray.asm
incsrc patches/freeze_enemies.asm
incsrc patches/ride_enemies.asm
incsrc patches/death_quota.asm
incsrc patches/enemy_drops.asm
incsrc patches/boss_exit_fix.asm
incsrc patches/spike_damage.asm
incsrc patches/hud_item_colors.asm
incsrc patches/underwater_blue_suit.asm
incsrc patches/english_only.asm
incsrc patches/grapple_bug_fixes.asm
incsrc patches/grapple_all_enemies.asm
if !USE_HITBOX_VIEWER
  incsrc patches/grapple_hitbox_viewer.asm
endif
incsrc bosses/torizos.asm
incsrc bosses/spore_spawn.asm
incsrc bosses/ceres.asm
incsrc bosses/kraid.asm
incsrc bosses/crocomire.asm
incsrc bosses/phantoon.asm
incsrc bosses/botwoon.asm
incsrc bosses/draygon.asm
incsrc bosses/ridley.asm
incsrc bosses/mother_brain.asm
incsrc enemies/samus_statue.asm
incsrc enemies/fune.asm
incsrc enemies/zebetite.asm
incsrc enemies/baby.asm
incsrc enemies/baby_top.asm
incsrc enemies/small_baby.asm
incsrc enemies/gunship.asm
incsrc enemies/water_zoomer.asm
incsrc projectiles/transporter_electricity.asm
incsrc projectiles/falling_drop.asm
incsrc plm/blue_suit_block.asm
incsrc plm/power_control.asm
incsrc plm/eye_door.asm
incsrc plm/animals_escape.asm
incsrc plm/ammo_station.asm
incsrc src/fx/waterflea.asm
incsrc src/fx/tourian_escape_palette_fx.asm
incsrc rooms/pit_room.asm
incsrc rooms/climb.asm
incsrc rooms/bomb_torizo.asm
incsrc rooms/early_supers.asm
incsrc rooms/green_brinstar_firefleas.asm
incsrc rooms/spore_spawn_kihunters.asm
incsrc rooms/spore_spawn.asm
incsrc rooms/noob_bridge.asm
incsrc rooms/bat_room.asm
incsrc rooms/below_spazer.asm
incsrc rooms/hi_jump_boots.asm
incsrc rooms/warehouse_zeelas.asm
incsrc rooms/warehouse_entrance.asm
incsrc rooms/kraid_kihunters.asm
incsrc rooms/mini_kraid.asm
incsrc rooms/kraid_eye_door.asm
incsrc rooms/kraid.asm
incsrc rooms/rising_tide.asm
incsrc rooms/bat_cave.asm
incsrc rooms/speed_hallway.asm
incsrc rooms/red_tower.asm
incsrc rooms/hellway.asm
incsrc rooms/alpha_power_bombs.asm
incsrc rooms/moat.asm
incsrc rooms/west_ocean.asm
incsrc rooms/main_shaft.asm
incsrc rooms/phantoon.asm
incsrc rooms/bowling.asm
incsrc rooms/spiky_room.asm
incsrc rooms/wrecked_ship_etank.asm
incsrc rooms/east_ocean.asm
incsrc rooms/crab_maze.asm
incsrc rooms/bug_sand_hole.asm
incsrc rooms/plasma_spark_room.asm
incsrc rooms/east_sand_hall.asm
incsrc rooms/west_sand_hall.asm
incsrc rooms/pants_room_a.asm
incsrc rooms/pants_room_b.asm
incsrc rooms/crocomire_speedway.asm
incsrc rooms/crocomire.asm
incsrc rooms/double_chamber.asm
incsrc rooms/spiky_acid_snakes.asm
incsrc rooms/crab_shaft.asm
incsrc rooms/botwoon.asm
incsrc rooms/botwoon_etank.asm
incsrc rooms/halfie_climb.asm
incsrc rooms/colosseum.asm
incsrc rooms/draygon.asm
incsrc rooms/east_cactus_alley.asm
incsrc rooms/butterfly_room.asm
incsrc rooms/main_hall.asm
incsrc rooms/acid_statue.asm
incsrc rooms/pillars.asm
incsrc rooms/writg.asm
incsrc rooms/red_kihunter_shaft.asm
incsrc rooms/wasteland.asm
incsrc rooms/ridley.asm
incsrc rooms/ridley_etank.asm
incsrc rooms/firefleas.asm
incsrc rooms/spring_ball_maze.asm
incsrc rooms/dust_torizo.asm
incsrc rooms/big_boy.asm
incsrc rooms/tourian_escape_1.asm
incsrc rooms/tourian_escape_2.asm
incsrc rooms/tourian_escape_3.asm
incsrc rooms/tourian_escape_4.asm
incsrc rooms/parlor.asm
incsrc rooms/landing_site.asm
incsrc rooms/flyway.asm
incsrc rooms/below_landing_site.asm
incsrc rooms/red_brinstar_fireflea.asm
incsrc rooms/volcano_room.asm
incsrc rooms/ice_beam_snakes.asm
incsrc rooms/spring_ball.asm
incsrc rooms/left_sandpit.asm
incsrc rooms/right_sandpit.asm
incsrc rooms/dead_scientist_room.asm
incsrc cinematic/escape.asm
incsrc cinematic/intro_text.asm
incsrc cinematic/intro.asm
incsrc cinematic/credits_text.asm
incsrc cinematic/credits.asm
incsrc title/title.asm
incsrc title/title_menu_text.asm
incsrc title/options_menu.asm
incsrc title/baby_arrow.asm
incsrc title/title_text.asm
incsrc title/from_planet_sr388.asm

incsrc metconst/CrashHandler.asm

%VALIDATE_FREESPACE()
