!debug_flag = $7E0DE0

lorom

incsrc freespace.asm
incsrc enemies.asm
incsrc physics_constants.asm
incsrc patches/freeze_enemies.asm
incsrc patches/ride_enemies.asm
incsrc patches/death_quota.asm
incsrc patches/enemy_drops.asm
incsrc patches/easy_blue_suit.asm
incsrc patches/boss_exit_fix.asm
incsrc bosses/torizos.asm
incsrc bosses/spore_spawn.asm
incsrc bosses/ceres.asm
incsrc bosses/kraid.asm
incsrc bosses/phantoon.asm
incsrc bosses/botwoon.asm
incsrc bosses/draygon.asm
incsrc enemies/samus_statue.asm
incsrc enemies/fune.asm
incsrc projectiles/transporter_electricity.asm
incsrc plm/blue_suit_block.asm
incsrc rooms/climb.asm
incsrc rooms/pit_room.asm
incsrc rooms/early_supers.asm
incsrc rooms/noob_bridge.asm
incsrc rooms/bat_room.asm
incsrc rooms/below_spazer.asm
incsrc rooms/warehouse_entrance.asm
incsrc rooms/rising_tide.asm
incsrc rooms/bat_cave.asm
incsrc rooms/speed_hallway.asm
incsrc rooms/red_tower.asm
incsrc rooms/hellway.asm
incsrc rooms/alpha_power_bombs.asm
incsrc rooms/moat.asm
incsrc rooms/west_ocean.asm
incsrc rooms/bowling.asm
incsrc rooms/spiky_room.asm
incsrc rooms/wrecked_ship_etank.asm
incsrc rooms/east_ocean.asm
incsrc rooms/crab_maze.asm
incsrc rooms/bug_sand_hole.asm
incsrc rooms/plasma_spark_room.asm
incsrc rooms/east_sand_hall.asm
incsrc rooms/west_sand_hall.asm
incsrc rooms/pants_room_a.asm
incsrc rooms/pants_room_b.asm
incsrc rooms/crocomire_speedway.asm
incsrc rooms/spiky_acid_snakes.asm
incsrc rooms/crab_shaft.asm
incsrc rooms/botwoon.asm
incsrc rooms/botwoon_etank.asm
incsrc rooms/halfie_climb.asm
incsrc rooms/colosseum.asm
incsrc rooms/draygon.asm
incsrc rooms/east_cactus_alley.asm
incsrc rooms/butterfly_room.asm
