!USE_BELOW_LANDING_SITE = 0

lorom

incsrc freespace.asm
incsrc enemies.asm
incsrc physics_constants.asm
incsrc patches/freeze_enemies.asm
incsrc patches/ride_enemies.asm
incsrc patches/death_quota.asm
incsrc patches/enemy_drops.asm
incsrc patches/easy_blue_suit.asm
incsrc patches/boss_exit_fix.asm
incsrc patches/spike_damage.asm
incsrc patches/ammo_station.asm
incsrc bosses/torizos.asm
incsrc bosses/spore_spawn.asm
incsrc bosses/ceres.asm
incsrc bosses/kraid.asm
incsrc bosses/crocomire.asm
incsrc bosses/phantoon.asm
incsrc bosses/botwoon.asm
incsrc bosses/draygon.asm
incsrc bosses/ridley.asm
incsrc bosses/mother_brain.asm
incsrc enemies/samus_statue.asm
incsrc enemies/fune.asm
incsrc enemies/zebetite.asm
incsrc enemies/baby.asm
incsrc enemies/baby_top.asm
incsrc projectiles/transporter_electricity.asm
incsrc plm/blue_suit_block.asm
incsrc plm/power_control.asm
incsrc plm/eye_door.asm
incsrc plm/animals_escape.asm
incsrc rooms/pit_room.asm
incsrc rooms/climb.asm
incsrc rooms/bomb_torizo.asm
incsrc rooms/early_supers.asm
incsrc rooms/green_brinstar_firefleas.asm
incsrc rooms/spore_spawn_kihunters.asm
incsrc rooms/spore_spawn.asm
incsrc rooms/noob_bridge.asm
incsrc rooms/bat_room.asm
incsrc rooms/below_spazer.asm
incsrc rooms/hi_jump_boots.asm
incsrc rooms/mini_kraid.asm
incsrc rooms/kraid_eye_door.asm
incsrc rooms/kraid.asm
incsrc rooms/warehouse_entrance.asm
incsrc rooms/kraid_kihunters.asm
incsrc rooms/kraid.asm
incsrc rooms/rising_tide.asm
incsrc rooms/bat_cave.asm
incsrc rooms/speed_hallway.asm
incsrc rooms/red_tower.asm
incsrc rooms/hellway.asm
incsrc rooms/alpha_power_bombs.asm
incsrc rooms/moat.asm
incsrc rooms/west_ocean.asm
incsrc rooms/phantoon.asm
incsrc rooms/bowling.asm
incsrc rooms/spiky_room.asm
incsrc rooms/wrecked_ship_etank.asm
incsrc rooms/east_ocean.asm
incsrc rooms/crab_maze.asm
incsrc rooms/bug_sand_hole.asm
incsrc rooms/plasma_spark_room.asm
incsrc rooms/east_sand_hall.asm
incsrc rooms/west_sand_hall.asm
incsrc rooms/pants_room_a.asm
incsrc rooms/pants_room_b.asm
incsrc rooms/crocomire_speedway.asm
incsrc rooms/crocomire.asm
incsrc rooms/double_chamber.asm
incsrc rooms/spiky_acid_snakes.asm
incsrc rooms/crab_shaft.asm
incsrc rooms/botwoon.asm
incsrc rooms/botwoon_etank.asm
incsrc rooms/halfie_climb.asm
incsrc rooms/colosseum.asm
incsrc rooms/draygon.asm
incsrc rooms/east_cactus_alley.asm
incsrc rooms/butterfly_room.asm
incsrc rooms/acid_statue.asm
incsrc rooms/pillars.asm
incsrc rooms/writg.asm
incsrc rooms/red_kihunter_shaft.asm
incsrc rooms/wasteland.asm
incsrc rooms/ridley_etank.asm
incsrc rooms/firefleas.asm
incsrc rooms/spring_ball_maze.asm
incsrc rooms/tourian_escape_1.asm
incsrc rooms/tourian_escape_2.asm
incsrc rooms/tourian_escape_3.asm
incsrc rooms/tourian_escape_4.asm
incsrc rooms/parlor.asm
incsrc rooms/landing_site.asm
incsrc rooms/flyway.asm
incsrc rooms/below_landing_site.asm
